// <auto-generated />
using System;
using AmbientWeather.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmbientWeather.Infrastructure.Migrations
{
    [DbContext(typeof(AmbientWeatherDbContext))]
    [Migration("20260529200949_AddSchemaInvariants")]
    partial class AddSchemaInvariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmbientWeather.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProviderSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth_provider_sub");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("AuthProviderSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.DashboardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_layouts_user_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("dashboard_layouts", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.NeighbourStationCache", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<double>("DistanceMiles")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_miles");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint")
                        .HasColumnName("rank");

                    b.HasKey("UserId", "StationId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId", "Rank")
                        .IsUnique();

                    b.ToTable("neighbour_station_cache", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.UserAmbientCredentials", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<string>("ApplicationKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_key_encrypted");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_ambient_credentials", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("DefaultWeatherStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_weather_station_id");

                    b.Property<string>("NeighbourConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("neighbour_config_json");

                    b.Property<string>("PressureUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("pressure_unit");

                    b.Property<string>("RainfallUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("rainfall_unit");

                    b.Property<string>("SpeedUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("speed_unit");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("temperature_unit");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("DefaultWeatherStationId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.WeatherReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BaromAbsIn")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("BaromRelIn")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<int?>("BattOut")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DailyRainIn")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DateUtc")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceMacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<double?>("DewPoint")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("DewPointIn")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("EventRainIn")
                        .HasPrecision(5, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("FeelsLike")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("FeelsLikeIn")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("HourlyRainIn")
                        .HasPrecision(5, 3)
                        .HasColumnType("double precision");

                    b.Property<int?>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int?>("HumidityIn")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRain")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MaxDailyGust")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("MonthlyRainIn")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadiation")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StoredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TempF")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("TempInF")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalRainIn")
                        .HasPrecision(8, 3)
                        .HasColumnType("double precision");

                    b.Property<string>("Tz")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Uv")
                        .HasColumnType("integer");

                    b.Property<double?>("WeeklyRainIn")
                        .HasPrecision(6, 3)
                        .HasColumnType("double precision");

                    b.Property<int?>("WindDir")
                        .HasColumnType("integer");

                    b.Property<double?>("WindGustMph")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMph")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DeviceMacAddress", "CreatedAtUtc");

                    b.HasIndex("DeviceMacAddress", "DateUtc")
                        .IsDescending(false, true);

                    b.ToTable("weather_readings", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("DisplayOnDashboard")
                        .HasColumnType("boolean")
                        .HasColumnName("display_on_dashboard");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_m");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("LastSyncAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nickname");

                    b.Property<string>("SelectedMetricKeysJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_metric_keys_json");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_weather_stations_user_primary")
                        .HasFilter("is_primary = true");

                    b.HasIndex("UserId", "MacAddress")
                        .IsUnique();

                    b.ToTable("weather_stations", (string)null);
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.DashboardLayout", b =>
                {
                    b.HasOne("AmbientWeather.Domain.Entities.AppUser", "User")
                        .WithMany("DashboardLayouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.NeighbourStationCache", b =>
                {
                    b.HasOne("AmbientWeather.Domain.Entities.WeatherStation", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmbientWeather.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.UserAmbientCredentials", b =>
                {
                    b.HasOne("AmbientWeather.Domain.Entities.AppUser", "User")
                        .WithOne("AmbientCredentials")
                        .HasForeignKey("AmbientWeather.Domain.Entities.UserAmbientCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("AmbientWeather.Domain.Entities.WeatherStation", "DefaultWeatherStation")
                        .WithMany()
                        .HasForeignKey("DefaultWeatherStationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AmbientWeather.Domain.Entities.AppUser", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("AmbientWeather.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultWeatherStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.WeatherStation", b =>
                {
                    b.HasOne("AmbientWeather.Domain.Entities.AppUser", "User")
                        .WithMany("WeatherStations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AmbientWeather.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AmbientCredentials");

                    b.Navigation("DashboardLayouts");

                    b.Navigation("Preferences");

                    b.Navigation("WeatherStations");
                });
#pragma warning restore 612, 618
        }
    }
}
